### PR TITLE
Replace instances of [mM]aster with [mM]ain, w/ fallbacks; Fixes #42

### LINKED ISSUE #42: AudioDevice+VirtualMasterOutput.swift + XCode 13 = fail
XCode 13 won't compile `AudioDevice+VirtualMasterOutput.swift` because of the error `'kAudioHardwareServiceDeviceProperty_VirtualMasterVolume' has been renamed to 'kAudioHardwareServiceDeviceProperty_VirtualMainVolume': APIs deprecated as of macOS 10.9 and earlier are unavailable in Swift`

Renaming every ...`_VirutalMasterVolume` to ...`_VirtualMainVolume` and every ...`_VirtualMasterBalance` to ...`_VirtualMainBalance` in the  file fixes the issue.

Thank you!

### PR DESCRIPTION
**Pull request by donaldguy**
Like the changelog entry says, upstream has changed, so this should follow suit.

As #42 notes, Xcode 13 beta won't build 4.0.1 as a dependency on Monterey as is

### CODE REVIEW

File: Sources/SimplyCoreAudio/Public/SimplyCoreAudio+Aggregate.swift [hunk 1]
```diff
@@ -14,31 +14,31 @@ import os.log
 public extension SimplyCoreAudio {
     /// This routine creates a new aggregate audio device.
     ///
-    /// - Parameter masterDeviceUID: An audio device. This will also be the clock source.
-    /// - Parameter secondDeviceUID: An audio device.
+    /// - Parameter mainDevice: An audio device. This will also be the clock source.
+    /// - Parameter secondDevice: An audio device.
```
Comment (donaldguy) [inline Sources/SimplyCoreAudio/Public/SimplyCoreAudio+Aggregate.swift:18]: Also changed this to match method signature

File: Sources/SimplyCoreAudio/Public/SimplyCoreAudio+Aggregate.swift [hunk 2]
```diff
@@ -51,6 +51,15 @@ public extension SimplyCoreAudio {
 
         return AudioDevice.lookup(by: deviceID)
     }
+    
+    @available(*, deprecated, message: "mainDevice: is preferred spelling for first argument")
```
Comment (donaldguy) [inline Sources/SimplyCoreAudio/Public/SimplyCoreAudio+Aggregate.swift:55]: not sure if there is a way to achieve auto-fixable warning for this (as with `renamed:` for signatures where appears in name vs args)

File: Sources/SimplyCoreAudio/Public/Enums/Scope.swift [hunk 3]
```diff
@@ -28,12 +28,16 @@ public enum Scope {
     /// side of an object.
     case playthrough
 
-    /// The AudioObjectPropertyElement value for properties that apply to the master
-    /// element or to the entire scope.
+    /// The AudioObjectPropertyElement value for properties that apply to the main
+    /// element or to the entire scope. Using deprecated naming
```
Comment (donaldguy) [inline Sources/SimplyCoreAudio/Public/Enums/Scope.swift:32]: I don't believe `@available` is valid here, hence why I didn't add it; but I could be wrong

File: Sources/SimplyCoreAudio/Public/Enums/Scope.swift [hunk 4]
```diff
@@ -28,12 +28,16 @@ public enum Scope {
...
     case master
 
     /// The wildcard value for AudioObjectPropertySelectors
     case wildcard
+    
+    /// The AudioObjectPropertyElement value for properties that apply to the main
+    /// element or to the entire scope.
+    case main
```
Comment (donaldguy) [inline Sources/SimplyCoreAudio/Public/Enums/Scope.swift:40]: Added at bottom of list for potential? binary compatibility on dylib usage

May be cargo-culting C idiom needlessly (am not _really_ Swift literate); feel free to re-alphabetize if you know better

File: Sources/SimplyCoreAudio/Public/Enums/Scope.swift [hunk 5]
```diff
@@ -45,7 +49,7 @@ extension Scope {
         case .input: return kAudioObjectPropertyScopeInput
         case .output: return kAudioObjectPropertyScopeOutput
         case .playthrough: return kAudioObjectPropertyScopePlayThrough
-        case .master: return kAudioObjectPropertyElementMaster
+        case .main, .master: return kAudioObjectPropertyElementMain
```
Comment (donaldguy) [inline Sources/SimplyCoreAudio/Public/Enums/Scope.swift:52]: may still want to return deprecated `kAudioObjectPropertyElementMaster` for `.master` — but since implementation is using Main now, seemed better to keep it consistent

File: Sources/SimplyCoreAudio/Public/Enums/Scope.swift [hunk 6]
```diff
@@ -57,6 +61,7 @@ extension Scope {
         case kAudioObjectPropertyScopeOutput: return .output
         case kAudioObjectPropertyScopePlayThrough: return .playthrough
         case kAudioObjectPropertyElementMaster: return .master
```
Comment (donaldguy) [inline Sources/SimplyCoreAudio/Public/Enums/Scope.swift:63]: could prefer for this to return `.main`; as a runtime concern, don't know it would matter; but there is a break in ~invertibility between this and the above

**Review by donaldguy — COMMENTED** [review]
Reasonable opinions may differ on whether it's worth duplicating tests to exercise deprecated method names

**Comment by donaldguy** [comment]
Tests are all good for me, btw:

[Test-SimplyCoreAudio-2021.07.30_18-39-01--0400.xcresult.zip](https://github.com/rnine/SimplyCoreAudio/files/6910217/Test-SimplyCoreAudio-2021.07.30_18-39-01--0400.xcresult.zip)

**Comment by rnine** [comment]
Thanks for the heads up. Merged!
